### ISSUE TITLE
An improper locking due to the unreleased lock before program exit

### ISSUE THREAD

**Issue by ryancaicse** [fumiyas/hyperestraier-encore#1]
Hi developers, in the below codes, the lock` log_mutex` could be not released before program's exit `atexit(log_close);` . I think there is no harm to `pthread_mutex_unlock(&log_mutex);`  before the `atexit(log_close);` for better resource management and code symmetry, albeit some common OS would release the resource. Thanks!

https://github.com/fumiyas/hyperestraier-encore/blob/3b09726c9b39998228fb0bcde5eec31fb0408e63/mastermod.c#L59-L97

**Comment by ryancaicse** [comment]
Hi, developers, any comments are highly appreciated!
@fumiyas

**Comment by fumiyas** [comment]
Modern operating systems free all resources for a process at exiting the process, and HyperEstrainer supports such OSes only. Thanks.
