### ISSUE TITLE
Missing closing files?

### ISSUE THREAD

**Issue by ryancaicse** [fumiyas/hyperestraier-encore#2]
The file at Line 4083 is not closed?
https://github.com/fumiyas/hyperestraier-encore/blob/3b09726c9b39998228fb0bcde5eec31fb0408e63/estraier.c#L4079-L4095

**Comment by ryancaicse** [comment]
Could you take a look? Many thanks. @fumiyas

**Comment by fumiyas** [comment]
It is closed by `est_random_fclose()` at process termination. See `atexit`(3).

**Comment by fumiyas** [comment]
It is closed by `est_random_fclose()` at process termination. See `atexit`(3).
