### ISSUE TITLE
Missing closing files

### ISSUE THREAD

**Issue by ryancaicse** [fumiyas/hyperestraier-encore#3]
`fopen("/dev/urandom", "rb")) != NULL` shoule be closed in the method `est_random`?
https://github.com/fumiyas/hyperestraier-encore/blob/3b09726c9b39998228fb0bcde5eec31fb0408e63/estraier.c#L4079-L4095

**Comment by ryancaicse** [comment]
Could you take a look? Many thanks. @fumiyas

**Comment by fumiyas** [comment]
Duplicate of #2.
